wget -qO- "http://localhost:10000/addUser?nick"
echo ""
wget -qO- "http://localhost:10000/addUser?anna"
echo ""
wget -qO- "http://localhost:10000/addFriend?nick&anna"
echo ""
wget -qO- "http://localhost:10000/getNearbyFriends?nick"
echo ""
wget -qO- "http://localhost:10000/updatePerson?anna&400&300"
echo ""
wget -qO- "http://localhost:10000/getNearbyFriends?nick"
echo ""
